### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by alankjackson** [slu-openGIS/postmastr#10]
My test data has both census addresses and google addresses so that the street and city names can either be all caps, or mixed case. Some options or tools for handling case would be nice. Perhaps something as simple as an option for the city dictionary to automagically add upper case equivalents to entered mixed-case city names? I expect this may become an issue when I start playing with street names too.

**Comment by chris-prener** [comment]
I just added this flexibility, but right now it relies on the initial city list being built with `tidycensus` - I'm not thrilled with this solution but hopefully that works for now!

As an aside - we pushed some breaking changes today that allow for intersections to be parsed as well. The `README.md` and the home page of the website have both been updated with a quick description of these changes.
