### ISSUE TITLE
pm_prep not found

### ISSUE THREAD

**Issue by alankjackson** [slu-openGIS/postmastr#3]
reprexdata <- tribble(
  ~address,
  "1230 TRAVIS ST, HOUSTON, TX, 77002",
  "3830 RICHMOND AVE, HOUSTON, TX, 77027"
)

df <- pm_identify(reprexdata, var = "address")
df
df <- pm_prep(df, var = "address")

Error in pm_prep(df, var = "address") : could not find function "pm_prep"

**Comment by chris-prener** [comment]
fixed @alankjackson - it wasn't being exported! sorry about that.
