### ISSUE TITLE
Geocoding in Mexico

### ISSUE THREAD

**Issue by fdzul** [slu-openGIS/postmastr#7]
**Before you open your issue:**
* All issues and contributions are covered by the [Code of Conduct](/.github/CODE_OF_CONDUCT.md)
* Please check out the [Contribution guidelines](/.github/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Provide a reprex**
Please include a minimal reproducible example (AKA a reprex). If you've never
heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading
<https://www.tidyverse.org/help/#reprex>. When you create your reprex, please use a data set available in a package.

```r
How can I help to work on the directions of Mexico?
```

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-prener** [comment]
Thanks for reaching out @fdzul - does Correos de México have an address standard similar to USPS?
